const express = require("express");
const grosseries = require("./routes/grossery/grosseries");
const addGrosseries = require("./routes/grossery/addGrosseries");
const grossery = require("./routes/grossery/grossery");
const listNames = require("./routes/listNames");

const Products = require("./routes/Products");
const Byu = require("./routes/Byu");
const storeStock = require("./routes/StoreStock");
const clientStock = require("./routes/ClientStock");
const store_transaction = require("./routes/store_transaction");
const st_owner = require("./routes/Owner");
const st_worker = require("./routes/Worker");
const family = require("./routes/Family");
const father = require("./routes/Father");
const daughter = require("./routes/Daughter");
const mother = require("./routes/Mother");
const storeWorker = require("./routes/storeWorker");

const son = require("./routes/Son");
const store = require("./routes/Store");
const supplier = require("./routes/supplier");
const supplierWorker = require("./routes/supplierWorker");
const manifacture = require("./routes/manifacture");
const manifactureWorker = require("./routes/manifactureWorker");
const supplierOwner = require("./routes/supplierOwner");
const manifactureOwner = require("./routes/manifactureOwner");
const store_stockAlert = require("./routes/StoreStockAlert");
const store_perimationAlert = require("./routes/StorePerimationAlert");
const store_global_stock = require("./routes/globalStoreStock");
const self_serving_list = require("./routes/self_serving_list");
const self_serving_products = require("./routes/self_serving_products");
const cash_transaction = require("./routes/cash_transaction");
const store_transaction_prod = require("./routes/store_transaction_prod");
const store_listNames = require("./routes/store_listNames");
const store_manual_order_list = require("./routes/store_manual_order_list");
const store_manual_order_products =
 require("./routes/store_manual_order_products");
 const store_list_order = require("./routes/store_list_order");
const store_order_products =
 require("./routes/store_order_products")
const client_listNames = require("./routes/client_listNames");
const client_products = require("./routes/client_products");
const sell_listNames = require("./routes/sell_listNames");
const sell_products = require("./routes/sell_Products");
const users = require("./routes/users");
const user = require("./routes/user");
const auth = require("./routes/auth");
const my = require("./routes/my");
const  bodyParser = require('body-parser')
const messages = require("./routes/messages");
const expoPushTokens = require("./routes/expoPushTokens");
const helmet = require("helmet");
const compression = require("compression");
const app = express();
const config=require("./startup/db");
app.use(express.urlencoded({extended:true}));
app.use(helmet());
app.use(compression());
app.use('/public',express.static("public"));
app.use("/api/grossery", grossery);
app.use("/api/grosseries", grosseries);
app.use("/api/grosseries_temp", addGrosseries);
app.use("/api/listNames", listNames);
app.use("/api/st_trans", store_transaction);
app.use("/api/st_owner", st_owner);
app.use("/api/st_worker", st_worker);
app.use("/api/family",family);
app.use("/api/father",father);
app.use("/api/son",son);
app.use("/api/storeWorker",storeWorker);
app.use("/api/daughter",daughter);
app.use("/api/mother",mother);
app.use("/api/store", store);
app.use("/api/supplier",supplier);
app.use("/api/supplierWorker",supplierWorker);
app.use("/api/manifacture",manifacture);
app.use("/api/manifactureWorker",manifactureWorker);
app.use("/api/supplierOwner",supplierOwner);
app.use("/api/manifactureOwner",manifactureOwner);
app.use("/api/st_stock_alert", store_stockAlert);
app.use("/api/st_perimation_alert", store_perimationAlert);
app.use("/api/st_global_stock", store_global_stock);
app.use("/api/client_stock", clientStock);
app.use("/api/self_serving", self_serving_list);
app.use("/api/self_serving_prod", self_serving_products);
app.use("/api/cash_trans", cash_transaction);
app.use("/api/st_trans_prod", store_transaction_prod);
app.use("/api/st_man_order_list", store_manual_order_list);
app.use("/api/st_order_list", store_list_order);
app.use("/api/st_man_order_products", store_manual_order_products);
app.use("/api/st_order_products", store_order_products);
app.use("/api/st_listNames", store_listNames);
app.use("/api/sell_listNames", sell_listNames);
app.use("/api/sell_products", sell_products);
app.use("/api/client_listNames", client_listNames);
app.use("/api/client_products", client_products);
app.use("/api/products", Products);
app.use("/api/byu", Byu);
app.use("/api/storeStock", storeStock);
app.use("/api/user", user);
app.use("/api/users", users);
app.use("/api/auth", auth);
app.use("/api/my", my);
app.use("/api/expoPushTokens", expoPushTokens);
app.use("/api/messages", messages);
const port = process.env.PORT || 9000
app.listen(port, function() {
  console.log(`Server started on port ${port}...`);
});
